name: sqlite_scripts_generator

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  build_config: ^1.1.1
  source_gen: ^1.2.6
  sqlite_scripts_annotation: ^1.0.0

dependency_overrides:
  sqlite_scripts_annotation:
    path: ../sqlite_scripts_annotation
dev_dependencies:
  build_runner: ^2.3.2
